version: '3'
services:
  docker-organize:
    image: docker-organize:latest
    container_name: organize
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./Output:/home/pi/Output
      - ./Input:/home/pi/Input
      - ./log:/var/log/organize/
      - ./config/:/home/pi/.config/organize/
